In [1]:
from mlxtend.preprocessing import TransactionEncoder
from mlxtend.frequent_patterns import apriori, fpgrowth
from mlxtend.frequent_patterns import association_rules
import pandas as pd
import ast

In [2]:
df_carts = pd.read_csv("../../data/tesco/tesco_carts_clean.csv")
df_inventory = pd.read_csv("../../data/tesco/tesco_inventory_clean.csv")

In [3]:
df_carts.head()

   cart_id                                               cart
0        0                                         [73314923]
1        1  [58175124, 50502269, 70943424, 57346955, 56036...
2        2  [50962501, 50503297, 50507984, 50169663, 51965...
3        3                     [72680530, 62284801, 58098273]
4        4           [56373768, 67336474, 52844621, 54921285]

In [4]:
df_inventory.head()

,product_id,category,description,ingredients,energy,fat,saturates,salt,sugars,protein,carbohydrate,fibre,avg_price
0,68238698,fruit_veg,Tesco Baby Corn 190G (M),no_ingredients,28.0,0.4,0.1,0.3,1.9,2.5,2.7,2.0,1.645
1,53426251,fruit_veg,Tesco Cranberries 100G,Pineapple Juice from Concentrate Cranberries S...,336.0,1.6,0.2,0.1,65.0,0.3,77.4,5.5,1.495
2,59445495,fruit_veg,Tesco Crispy Slices 350G,Potato (78%) Batter Rapeseed Oil Batter contai...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.500
3,74533881,sweets,Kelloggs Pop Tarts Frosted S'mores 416G,"Enriched Flour (Wheat Flour, Niacin, Reduced I...",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3.500
4,54198489,grains,Osem Bamba Peanut Snack 25G,Peanuts (50%) Corn Palm Oil Salt,534.0,34.0,6.6,1.0,3.2,0.0,0.0,0.0,0.400

To learn more about their customers’ behavior, the Tesco marketing department is interested in three
pieces of information.
- A list of triplets of products (A, B, C) such that C is purchased frequently after A and B. They are
interested in strong associations, such that the likelihood of the association is at least 1.8 times higher
than chance.
- A list of pairs (A, B) such that B is frequently purchased after A, and that the pair (A, B) is found
least in 0.5% of the carts.
- The top three items by confidence in the association rule A → B,

In [5]:
# Inspecting the carts dataset carts that contain more than a single item is a list but the list is in quotation marks which turns it into a string instead of a list
# which I can verify by simply grabbing one cart which multiple items and making python determine its type.
print(type(df_carts['cart'][1]))

<class 'str'>

In [6]:
# To convert the string representation of a list to a list I use ast.literal_eval, inspired from here: https://stackoverflow.com/questions/1894269/how-to-convert-string-representation-of-list-to-a-list
# and from what we did in exercises for lecture 5.
carts = df_carts['cart'].apply(ast.literal_eval).tolist()

In [7]:
# Verify that the same cart as before now actually has type list
print(type(carts[1]))

<class 'list'>

In [8]:
print(len(carts))

1582801

In [9]:
te = TransactionEncoder()
te_data = te.fit(carts).transform(carts, sparse=True)
df = pd.DataFrame.sparse.from_spmatrix(te_data, columns=te.columns_)

# product indices must either start from 0 or be strings
df.columns = [str(i) for i in df.columns]

In [10]:
# Very low minimum support because the dataset has 1.5m entries, a value of 0.05 found no triplets
frequent_itemsets = apriori(df, min_support=0.005, use_colnames=True, low_memory=True)

In [11]:
frequent_itemsets

      support                         itemsets
0    0.006962            frozenset({50068523})
1    0.007201            frozenset({50264481})
2    0.007234            frozenset({50314549})
3    0.005459            frozenset({50342538})
4    0.005873            frozenset({50461944})
..        ...                              ...
154  0.007180  frozenset({50502436, 77454543})
155  0.005193  frozenset({50503441, 50550228})
156  0.005349  frozenset({54550994, 50503441})
157  0.005358  frozenset({50503441, 62816594})
158  0.005325  frozenset({50550228, 62816594})

[159 rows x 2 columns]

In [12]:
rules = association_rules(frequent_itemsets, metric='lift', min_threshold=0.001)
rules

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,representativity,leverage,conviction,zhangs_metric,jaccard,certainty,kulczynski
0,frozenset({50502436}),frozenset({50502269}),0.054489,0.088677,0.016375,0.300528,3.389015,1.0,0.011543,1.302872,0.745553,0.129153,0.232465,0.242596
1,frozenset({50502269}),frozenset({50502436}),0.088677,0.054489,0.016375,0.184664,3.389015,1.0,0.011543,1.159658,0.773523,0.129153,0.137676,0.242596
2,frozenset({50503441}),frozenset({50502269}),0.036397,0.088677,0.009737,0.267528,3.016878,1.0,0.006510,1.244174,0.693783,0.084424,0.196254,0.188666
3,frozenset({50502269}),frozenset({50503441}),0.088677,0.036397,0.009737,0.109805,3.016878,1.0,0.006510,1.082463,0.733584,0.084424,0.076181,0.188666
4,frozenset({50550228}),frozenset({50502269}),0.020380,0.088677,0.006243,0.306352,3.454697,1.0,0.004436,1.313812,0.725321,0.060725,0.238856,0.188379
5,frozenset({50502269}),frozenset({50550228}),0.088677,0.020380,0.006243,0.070406,3.454697,1.0,0.004436,1.053815,0.779679,0.060725,0.051067,0.188379
6,frozenset({50652534}),frozenset({50502269}),0.024788,0.088677,0.007079,0.285569,3.220325,1.0,0.004880,1.275592,0.706997,0.066537,0.216050,0.182697
7,frozenset({50502269}),frozenset({50652534}),0.088677,0.024788,0.007079,0.079824,3.220325,1.0,0.004880,1.059811,0.756562,0.066537,0.056436,0.182697
8,frozenset({50689433}),frozenset({50502269}),0.032198,0.088677,0.007034,0.218472,2.463686,1.0,0.004179,1.166079,0.613869,0.061791,0.142425,0.148899
9,frozenset({50502269}),frozenset({50689433}),0.088677,0.032198,0.007034,0.079326,2.463686,1.0,0.004179,1.051188,0.651914,0.061791,0.048696,0.148899
10,frozenset({50962213}),frozenset({50502269}),0.015224,0.088677,0.005287,0.347305,3.916514,1.0,0.003937,1.396246,0.756183,0.053618,0.283794,0.203465
11,frozenset({50502269}),frozenset({50962213}),0.088677,0.015224,0.005287,0.059626,3.916514,1.0,0.003937,1.047217,0.817132,0.053618,0.045088,0.203465
12,frozenset({51114646}),frozenset({50502269}),0.014372,0.088677,0.005307,0.369263,4.164139,1.0,0.004033,1.444855,0.770934,0.054297,0.307889,0.214555
13,frozenset({50502269}),frozenset({51114646}),0.088677,0.014372,0.005307,0.059847,4.164139,1.0,0.004033,1.048370,0.833793,0.054297,0.046138,0.214555
14,frozenset({54169392}),frozenset({50502269}),0.035965,0.088677,0.005517,0.153412,1.730014,1.0,0.002328,1.076466,0.437712,0.046317,0.071035,0.107816
15,frozenset({50502269}),frozenset({54169392}),0.088677,0.035965,0.005517,0.062219,1.730014,1.0,0.002328,1.027997,0.463030,0.046317,0.027234,0.107816
16,frozenset({54550913}),frozenset({50502269}),0.040352,0.088677,0.005740,0.142244,1.604072,1.0,0.002162,1.062451,0.392422,0.046556,0.058780,0.103486
17,frozenset({50502269}),frozenset({54550913}),0.088677,0.040352,0.005740,0.064727,1.604072,1.0,0.002162,1.026062,0.413231,0.046556,0.025400,0.103486
18,frozenset({54550994}),frozenset({50502269}),0.061543,0.088677,0.010279,0.167016,1.883417,1.0,0.004821,1.094046,0.499810,0.073450,0.085962,0.141463
19,frozenset({50502269}),frozenset({54550994}),0.088677,0.061543,0.010279,0.115911,1.883417,1.0,0.004821,1.061496,0.514691,0.073450,0.057933,0.141463
20,frozenset({57810642}),frozenset({50502269}),0.017365,0.088677,0.006281,0.361688,4.078716,1.0,0.004741,1.427708,0.768164,0.062957,0.299577,0.216257
21,frozenset({50502269}),frozenset({57810642}),0.088677,0.017365,0.006281,0.070826,4.078716,1.0,0.004741,1.057536,0.828274,0.062957,0.054406,0.216257
22,frozenset({58175124}),frozenset({50502269}),0.017900,0.088677,0.005771,0.322427,3.635971,1.0,0.004184,1.344981,0.738184,0.057253,0.256495,0.193755
23,frozenset({50502269}),frozenset({58175124}),0.088677,0.017900,0.005771,0.065084,3.635971,1.0,0.004184,1.050468,0.795514,0.057253,0.048044,0.193755
24,frozenset({62816594}),frozenset({50502269}),0.029026,0.088677,0.008498,0.292776,3.301599,1.0,0.005924,1.288591,0.717956,0.077819,0.223959,0.194305
25,frozenset({50502269}),frozenset({62816594}),0.088677,0.029026,0.008498,0.095834,3.301599,1.0,0.005924,1.073888,0.764950,0.077819,0.068804,0.194305
26,frozenset({77454543}),frozenset({50502269}),0.019999,0.088677,0.005737,0.286843,3.234690,1.0,0.003963,1.277871,0.704950,0.055728,0.217448,0.175767
27,frozenset({50502269}),frozenset({77454543}),0.088677,0.019999,0.005737,0.064692,3.234690,1.0,0.003963,1.047784,0.758075,0.055728,0.045604,0.175767
28,frozenset({50502436}),frozenset({50503441}),0.054489,0.036397,0.008574,0.157354,4.323285,1.0,0.006591,1.143544,0.812994,0.104166,0.125526,0.196462
29,frozenset({50503441}),frozenset({50502436}),0.036397,0.054489,0.008574,0.235571,4.323285,1.0,0.006591,1.236885,0.797729,0.104166,0.191518,0.196462
30,frozenset({50502436}),frozenset({50550228}),0.054489,0.020380,0.005039,0.092469,4.537317,1.0,0.003928,1.079435,0.824533,0.072154,0.073589,0.169851
31,frozenset({50550228}),frozenset({50502436}),0.020380,0.054489,0.005039,0.247233,4.537317,1.0,0.003928,1.256048,0.795824,0.072154,0.203852,0.169851
32,frozenset({50502436}),frozenset({50652534}),0.054489,0.024788,0.011538,0.211746,8.542365,1.0,0.010187,1.237180,0.933819,0.170327,0.191710,0.338605
33,frozenset({50652534}),frozenset({50502436}),0.024788,0.054489,0.011538,0.465464,8.542365,1.0,0.010187,1.768843,0.905379,0.170327,0.434659,0.338605
34,frozenset({50502436}),frozenset({50689433}),0.054489,0.032198,0.008603,0.157887,4.903643,1.0,0.006849,1.149255,0.841947,0.110178,0.129871,0.212541
35,frozenset({50689433}),frozenset({50502436}),0.032198,0.054489,0.008603,0.267194,4.903643,1.0,0.006849,1.290261,0.822555,0.110178,0.224963,0.212541
36,frozenset({50502436}),frozenset({54550994}),0.054489,0.061543,0.007002,0.128494,2.087887,1.0,0.003648,1.076823,0.551074,0.064216,0.071342,0.121130
37,frozenset({54550994}),frozenset({50502436}),0.061543,0.054489,0.007002,0.113767,2.087887,1.0,0.003648,1.066887,0.555216,0.064216,0.062694,0.121130
38,frozenset({50502436}),frozenset({62816594}),0.054489,0.029026,0.007026,0.128947,4.442392,1.0,0.005445,1.114712,0.819553,0.091858,0.102907,0.185504
39,frozenset({62816594}),frozenset({50502436}),0.029026,0.054489,0.007026,0.242061,4.442392,1.0,0.005445,1.247476,0.798061,0.091858,0.198382,0.185504
40,frozenset({50502436}),frozenset({75341714}),0.054489,0.017185,0.006015,0.110383,6.423333,1.0,0.005078,1.104763,0.892975,0.091605,0.094828,0.230192
41,frozenset({75341714}),frozenset({50502436}),0.017185,0.054489,0.006015,0.350000,6.423333,1.0,0.005078,1.454633,0.859081,0.091605,0.312541,0.230192
42,frozenset({50502436}),frozenset({77454543}),0.054489,0.019999,0.007180,0.131764,6.588420,1.0,0.006090,1.128726,0.897101,0.106668,0.114046,0.245380
43,frozenset({77454543}),frozenset({50502436}),0.019999,0.054489,0.007180,0.358995,6.588420,1.0,0.006090,1.475046,0.865529,0.106668,0.322055,0.245380
44,frozenset({50503441}),frozenset({50550228}),0.036397,0.020380,0.005193,0.142686,7.001383,1.0,0.004452,1.142662,0.889548,0.100679,0.124851,0.198757
45,frozenset({50550228}),frozenset({50503441}),0.020380,0.036397,0.005193,0.254828,7.001383,1.0,0.004452,1.293129,0.875003,0.100679,0.226682,0.198757
46,frozenset({54550994}),frozenset({50503441}),0.061543,0.036397,0.005349,0.086921,2.388152,1.0,0.003109,1.055334,0.619385,0.057775,0.052433,0.116947
47,frozenset({50503441}),frozenset({54550994}),0.036397,0.061543,0.005349,0.146974,2.388152,1.0,0.003109,1.100150,0.603222,0.057775,0.091033,0.116947
48,frozenset({50503441}),frozenset({62816594}),0.036397,0.029026,0.005358,0.147217,5.071818,1.0,0.004302,1.138593,0.833156,0.089207,0.121723,0.165907
49,frozenset({62816594}),frozenset({50503441}),0.029026,0.036397,0.005358,0.184598,5.071818,1.0,0.004302,1.181753,0.826832,0.089207,0.153799,0.165907
50,frozenset({50550228}),frozenset({62816594}),0.020380,0.029026,0.005325,0.261308,9.002415,1.0,0.004734,1.314449,0.907411,0.120810,0.239225,0.222387
51,frozenset({62816594}),frozenset({50550228}),0.029026,0.020380,0.005325,0.183466,9.002415,1.0,0.004734,1.199731,0.915492,0.120810,0.166480,0.222387

In [17]:
# Code inspired by https://rasbt.github.io/mlxtend/user_guide/frequent_patterns/association_rules/
rules["antecedent_len"] = rules["antecedents"].apply(lambda x: len(x))
rules["consequents_len"] = rules["consequents"].apply(lambda x: len(x))
rules

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,representativity,leverage,conviction,zhangs_metric,jaccard,certainty,kulczynski,antecedent_len,consequents_len
0,frozenset({50502436}),frozenset({50502269}),0.054489,0.088677,0.016375,0.300528,3.389015,1.0,0.011543,1.302872,0.745553,0.129153,0.232465,0.242596,1,1
1,frozenset({50502269}),frozenset({50502436}),0.088677,0.054489,0.016375,0.184664,3.389015,1.0,0.011543,1.159658,0.773523,0.129153,0.137676,0.242596,1,1
2,frozenset({50503441}),frozenset({50502269}),0.036397,0.088677,0.009737,0.267528,3.016878,1.0,0.006510,1.244174,0.693783,0.084424,0.196254,0.188666,1,1
3,frozenset({50502269}),frozenset({50503441}),0.088677,0.036397,0.009737,0.109805,3.016878,1.0,0.006510,1.082463,0.733584,0.084424,0.076181,0.188666,1,1
4,frozenset({50550228}),frozenset({50502269}),0.020380,0.088677,0.006243,0.306352,3.454697,1.0,0.004436,1.313812,0.725321,0.060725,0.238856,0.188379,1,1
5,frozenset({50502269}),frozenset({50550228}),0.088677,0.020380,0.006243,0.070406,3.454697,1.0,0.004436,1.053815,0.779679,0.060725,0.051067,0.188379,1,1
6,frozenset({50652534}),frozenset({50502269}),0.024788,0.088677,0.007079,0.285569,3.220325,1.0,0.004880,1.275592,0.706997,0.066537,0.216050,0.182697,1,1
7,frozenset({50502269}),frozenset({50652534}),0.088677,0.024788,0.007079,0.079824,3.220325,1.0,0.004880,1.059811,0.756562,0.066537,0.056436,0.182697,1,1
8,frozenset({50689433}),frozenset({50502269}),0.032198,0.088677,0.007034,0.218472,2.463686,1.0,0.004179,1.166079,0.613869,0.061791,0.142425,0.148899,1,1
9,frozenset({50502269}),frozenset({50689433}),0.088677,0.032198,0.007034,0.079326,2.463686,1.0,0.004179,1.051188,0.651914,0.061791,0.048696,0.148899,1,1
10,frozenset({50962213}),frozenset({50502269}),0.015224,0.088677,0.005287,0.347305,3.916514,1.0,0.003937,1.396246,0.756183,0.053618,0.283794,0.203465,1,1
11,frozenset({50502269}),frozenset({50962213}),0.088677,0.015224,0.005287,0.059626,3.916514,1.0,0.003937,1.047217,0.817132,0.053618,0.045088,0.203465,1,1
12,frozenset({51114646}),frozenset({50502269}),0.014372,0.088677,0.005307,0.369263,4.164139,1.0,0.004033,1.444855,0.770934,0.054297,0.307889,0.214555,1,1
13,frozenset({50502269}),frozenset({51114646}),0.088677,0.014372,0.005307,0.059847,4.164139,1.0,0.004033,1.048370,0.833793,0.054297,0.046138,0.214555,1,1
14,frozenset({54169392}),frozenset({50502269}),0.035965,0.088677,0.005517,0.153412,1.730014,1.0,0.002328,1.076466,0.437712,0.046317,0.071035,0.107816,1,1
15,frozenset({50502269}),frozenset({54169392}),0.088677,0.035965,0.005517,0.062219,1.730014,1.0,0.002328,1.027997,0.463030,0.046317,0.027234,0.107816,1,1
16,frozenset({54550913}),frozenset({50502269}),0.040352,0.088677,0.005740,0.142244,1.604072,1.0,0.002162,1.062451,0.392422,0.046556,0.058780,0.103486,1,1
17,frozenset({50502269}),frozenset({54550913}),0.088677,0.040352,0.005740,0.064727,1.604072,1.0,0.002162,1.026062,0.413231,0.046556,0.025400,0.103486,1,1
18,frozenset({54550994}),frozenset({50502269}),0.061543,0.088677,0.010279,0.167016,1.883417,1.0,0.004821,1.094046,0.499810,0.073450,0.085962,0.141463,1,1
19,frozenset({50502269}),frozenset({54550994}),0.088677,0.061543,0.010279,0.115911,1.883417,1.0,0.004821,1.061496,0.514691,0.073450,0.057933,0.141463,1,1
20,frozenset({57810642}),frozenset({50502269}),0.017365,0.088677,0.006281,0.361688,4.078716,1.0,0.004741,1.427708,0.768164,0.062957,0.299577,0.216257,1,1
21,frozenset({50502269}),frozenset({57810642}),0.088677,0.017365,0.006281,0.070826,4.078716,1.0,0.004741,1.057536,0.828274,0.062957,0.054406,0.216257,1,1
22,frozenset({58175124}),frozenset({50502269}),0.017900,0.088677,0.005771,0.322427,3.635971,1.0,0.004184,1.344981,0.738184,0.057253,0.256495,0.193755,1,1
23,frozenset({50502269}),frozenset({58175124}),0.088677,0.017900,0.005771,0.065084,3.635971,1.0,0.004184,1.050468,0.795514,0.057253,0.048044,0.193755,1,1
24,frozenset({62816594}),frozenset({50502269}),0.029026,0.088677,0.008498,0.292776,3.301599,1.0,0.005924,1.288591,0.717956,0.077819,0.223959,0.194305,1,1
25,frozenset({50502269}),frozenset({62816594}),0.088677,0.029026,0.008498,0.095834,3.301599,1.0,0.005924,1.073888,0.764950,0.077819,0.068804,0.194305,1,1
26,frozenset({77454543}),frozenset({50502269}),0.019999,0.088677,0.005737,0.286843,3.234690,1.0,0.003963,1.277871,0.704950,0.055728,0.217448,0.175767,1,1
27,frozenset({50502269}),frozenset({77454543}),0.088677,0.019999,0.005737,0.064692,3.234690,1.0,0.003963,1.047784,0.758075,0.055728,0.045604,0.175767,1,1
28,frozenset({50502436}),frozenset({50503441}),0.054489,0.036397,0.008574,0.157354,4.323285,1.0,0.006591,1.143544,0.812994,0.104166,0.125526,0.196462,1,1
29,frozenset({50503441}),frozenset({50502436}),0.036397,0.054489,0.008574,0.235571,4.323285,1.0,0.006591,1.236885,0.797729,0.104166,0.191518,0.196462,1,1
30,frozenset({50502436}),frozenset({50550228}),0.054489,0.020380,0.005039,0.092469,4.537317,1.0,0.003928,1.079435,0.824533,0.072154,0.073589,0.169851,1,1
31,frozenset({50550228}),frozenset({50502436}),0.020380,0.054489,0.005039,0.247233,4.537317,1.0,0.003928,1.256048,0.795824,0.072154,0.203852,0.169851,1,1
32,frozenset({50502436}),frozenset({50652534}),0.054489,0.024788,0.011538,0.211746,8.542365,1.0,0.010187,1.237180,0.933819,0.170327,0.191710,0.338605,1,1
33,frozenset({50652534}),frozenset({50502436}),0.024788,0.054489,0.011538,0.465464,8.542365,1.0,0.010187,1.768843,0.905379,0.170327,0.434659,0.338605,1,1
34,frozenset({50502436}),frozenset({50689433}),0.054489,0.032198,0.008603,0.157887,4.903643,1.0,0.006849,1.149255,0.841947,0.110178,0.129871,0.212541,1,1
35,frozenset({50689433}),frozenset({50502436}),0.032198,0.054489,0.008603,0.267194,4.903643,1.0,0.006849,1.290261,0.822555,0.110178,0.224963,0.212541,1,1
36,frozenset({50502436}),frozenset({54550994}),0.054489,0.061543,0.007002,0.128494,2.087887,1.0,0.003648,1.076823,0.551074,0.064216,0.071342,0.121130,1,1
37,frozenset({54550994}),frozenset({50502436}),0.061543,0.054489,0.007002,0.113767,2.087887,1.0,0.003648,1.066887,0.555216,0.064216,0.062694,0.121130,1,1
38,frozenset({50502436}),frozenset({62816594}),0.054489,0.029026,0.007026,0.128947,4.442392,1.0,0.005445,1.114712,0.819553,0.091858,0.102907,0.185504,1,1
39,frozenset({62816594}),frozenset({50502436}),0.029026,0.054489,0.007026,0.242061,4.442392,1.0,0.005445,1.247476,0.798061,0.091858,0.198382,0.185504,1,1
40,frozenset({50502436}),frozenset({75341714}),0.054489,0.017185,0.006015,0.110383,6.423333,1.0,0.005078,1.104763,0.892975,0.091605,0.094828,0.230192,1,1
41,frozenset({75341714}),frozenset({50502436}),0.017185,0.054489,0.006015,0.350000,6.423333,1.0,0.005078,1.454633,0.859081,0.091605,0.312541,0.230192,1,1
42,frozenset({50502436}),frozenset({77454543}),0.054489,0.019999,0.007180,0.131764,6.588420,1.0,0.006090,1.128726,0.897101,0.106668,0.114046,0.245380,1,1
43,frozenset({77454543}),frozenset({50502436}),0.019999,0.054489,0.007180,0.358995,6.588420,1.0,0.006090,1.475046,0.865529,0.106668,0.322055,0.245380,1,1
44,frozenset({50503441}),frozenset({50550228}),0.036397,0.020380,0.005193,0.142686,7.001383,1.0,0.004452,1.142662,0.889548,0.100679,0.124851,0.198757,1,1
45,frozenset({50550228}),frozenset({50503441}),0.020380,0.036397,0.005193,0.254828,7.001383,1.0,0.004452,1.293129,0.875003,0.100679,0.226682,0.198757,1,1
46,frozenset({54550994}),frozenset({50503441}),0.061543,0.036397,0.005349,0.086921,2.388152,1.0,0.003109,1.055334,0.619385,0.057775,0.052433,0.116947,1,1
47,frozenset({50503441}),frozenset({54550994}),0.036397,0.061543,0.005349,0.146974,2.388152,1.0,0.003109,1.100150,0.603222,0.057775,0.091033,0.116947,1,1
48,frozenset({50503441}),frozenset({62816594}),0.036397,0.029026,0.005358,0.147217,5.071818,1.0,0.004302,1.138593,0.833156,0.089207,0.121723,0.165907,1,1
49,frozenset({62816594}),frozenset({50503441}),0.029026,0.036397,0.005358,0.184598,5.071818,1.0,0.004302,1.181753,0.826832,0.089207,0.153799,0.165907,1,1
50,frozenset({50550228}),frozenset({62816594}),0.020380,0.029026,0.005325,0.261308,9.002415,1.0,0.004734,1.314449,0.907411,0.120810,0.239225,0.222387,1,1
51,frozenset({62816594}),frozenset({50550228}),0.029026,0.020380,0.005325,0.183466,9.002415,1.0,0.004734,1.199731,0.915492,0.120810,0.166480,0.222387,1,1

In [20]:
rules[ (rules['antecedent_len'] >= 2) &
       (rules['lift'] > 1.8) ]

Empty DataFrame
Columns: [antecedents, consequents, antecedent support, consequent support, support, confidence, lift, representativity, leverage, conviction, zhangs_metric, jaccard, certainty, kulczynski, antecedent_len, consequents_len]
Index: []

In [21]:
rules[ (rules['antecedent_len'] == 1) & 
       (rules['consequents_len'] == 1) &
       (rules['support'] >= 0.005) ]

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,representativity,leverage,conviction,zhangs_metric,jaccard,certainty,kulczynski,antecedent_len,consequents_len
0,frozenset({50502436}),frozenset({50502269}),0.054489,0.088677,0.016375,0.300528,3.389015,1.0,0.011543,1.302872,0.745553,0.129153,0.232465,0.242596,1,1
1,frozenset({50502269}),frozenset({50502436}),0.088677,0.054489,0.016375,0.184664,3.389015,1.0,0.011543,1.159658,0.773523,0.129153,0.137676,0.242596,1,1
2,frozenset({50503441}),frozenset({50502269}),0.036397,0.088677,0.009737,0.267528,3.016878,1.0,0.006510,1.244174,0.693783,0.084424,0.196254,0.188666,1,1
3,frozenset({50502269}),frozenset({50503441}),0.088677,0.036397,0.009737,0.109805,3.016878,1.0,0.006510,1.082463,0.733584,0.084424,0.076181,0.188666,1,1
4,frozenset({50550228}),frozenset({50502269}),0.020380,0.088677,0.006243,0.306352,3.454697,1.0,0.004436,1.313812,0.725321,0.060725,0.238856,0.188379,1,1
5,frozenset({50502269}),frozenset({50550228}),0.088677,0.020380,0.006243,0.070406,3.454697,1.0,0.004436,1.053815,0.779679,0.060725,0.051067,0.188379,1,1
6,frozenset({50652534}),frozenset({50502269}),0.024788,0.088677,0.007079,0.285569,3.220325,1.0,0.004880,1.275592,0.706997,0.066537,0.216050,0.182697,1,1
7,frozenset({50502269}),frozenset({50652534}),0.088677,0.024788,0.007079,0.079824,3.220325,1.0,0.004880,1.059811,0.756562,0.066537,0.056436,0.182697,1,1
8,frozenset({50689433}),frozenset({50502269}),0.032198,0.088677,0.007034,0.218472,2.463686,1.0,0.004179,1.166079,0.613869,0.061791,0.142425,0.148899,1,1
9,frozenset({50502269}),frozenset({50689433}),0.088677,0.032198,0.007034,0.079326,2.463686,1.0,0.004179,1.051188,0.651914,0.061791,0.048696,0.148899,1,1
10,frozenset({50962213}),frozenset({50502269}),0.015224,0.088677,0.005287,0.347305,3.916514,1.0,0.003937,1.396246,0.756183,0.053618,0.283794,0.203465,1,1
11,frozenset({50502269}),frozenset({50962213}),0.088677,0.015224,0.005287,0.059626,3.916514,1.0,0.003937,1.047217,0.817132,0.053618,0.045088,0.203465,1,1
12,frozenset({51114646}),frozenset({50502269}),0.014372,0.088677,0.005307,0.369263,4.164139,1.0,0.004033,1.444855,0.770934,0.054297,0.307889,0.214555,1,1
13,frozenset({50502269}),frozenset({51114646}),0.088677,0.014372,0.005307,0.059847,4.164139,1.0,0.004033,1.048370,0.833793,0.054297,0.046138,0.214555,1,1
14,frozenset({54169392}),frozenset({50502269}),0.035965,0.088677,0.005517,0.153412,1.730014,1.0,0.002328,1.076466,0.437712,0.046317,0.071035,0.107816,1,1
15,frozenset({50502269}),frozenset({54169392}),0.088677,0.035965,0.005517,0.062219,1.730014,1.0,0.002328,1.027997,0.463030,0.046317,0.027234,0.107816,1,1
16,frozenset({54550913}),frozenset({50502269}),0.040352,0.088677,0.005740,0.142244,1.604072,1.0,0.002162,1.062451,0.392422,0.046556,0.058780,0.103486,1,1
17,frozenset({50502269}),frozenset({54550913}),0.088677,0.040352,0.005740,0.064727,1.604072,1.0,0.002162,1.026062,0.413231,0.046556,0.025400,0.103486,1,1
18,frozenset({54550994}),frozenset({50502269}),0.061543,0.088677,0.010279,0.167016,1.883417,1.0,0.004821,1.094046,0.499810,0.073450,0.085962,0.141463,1,1
19,frozenset({50502269}),frozenset({54550994}),0.088677,0.061543,0.010279,0.115911,1.883417,1.0,0.004821,1.061496,0.514691,0.073450,0.057933,0.141463,1,1
20,frozenset({57810642}),frozenset({50502269}),0.017365,0.088677,0.006281,0.361688,4.078716,1.0,0.004741,1.427708,0.768164,0.062957,0.299577,0.216257,1,1
21,frozenset({50502269}),frozenset({57810642}),0.088677,0.017365,0.006281,0.070826,4.078716,1.0,0.004741,1.057536,0.828274,0.062957,0.054406,0.216257,1,1
22,frozenset({58175124}),frozenset({50502269}),0.017900,0.088677,0.005771,0.322427,3.635971,1.0,0.004184,1.344981,0.738184,0.057253,0.256495,0.193755,1,1
23,frozenset({50502269}),frozenset({58175124}),0.088677,0.017900,0.005771,0.065084,3.635971,1.0,0.004184,1.050468,0.795514,0.057253,0.048044,0.193755,1,1
24,frozenset({62816594}),frozenset({50502269}),0.029026,0.088677,0.008498,0.292776,3.301599,1.0,0.005924,1.288591,0.717956,0.077819,0.223959,0.194305,1,1
25,frozenset({50502269}),frozenset({62816594}),0.088677,0.029026,0.008498,0.095834,3.301599,1.0,0.005924,1.073888,0.764950,0.077819,0.068804,0.194305,1,1
26,frozenset({77454543}),frozenset({50502269}),0.019999,0.088677,0.005737,0.286843,3.234690,1.0,0.003963,1.277871,0.704950,0.055728,0.217448,0.175767,1,1
27,frozenset({50502269}),frozenset({77454543}),0.088677,0.019999,0.005737,0.064692,3.234690,1.0,0.003963,1.047784,0.758075,0.055728,0.045604,0.175767,1,1
28,frozenset({50502436}),frozenset({50503441}),0.054489,0.036397,0.008574,0.157354,4.323285,1.0,0.006591,1.143544,0.812994,0.104166,0.125526,0.196462,1,1
29,frozenset({50503441}),frozenset({50502436}),0.036397,0.054489,0.008574,0.235571,4.323285,1.0,0.006591,1.236885,0.797729,0.104166,0.191518,0.196462,1,1
30,frozenset({50502436}),frozenset({50550228}),0.054489,0.020380,0.005039,0.092469,4.537317,1.0,0.003928,1.079435,0.824533,0.072154,0.073589,0.169851,1,1
31,frozenset({50550228}),frozenset({50502436}),0.020380,0.054489,0.005039,0.247233,4.537317,1.0,0.003928,1.256048,0.795824,0.072154,0.203852,0.169851,1,1
32,frozenset({50502436}),frozenset({50652534}),0.054489,0.024788,0.011538,0.211746,8.542365,1.0,0.010187,1.237180,0.933819,0.170327,0.191710,0.338605,1,1
33,frozenset({50652534}),frozenset({50502436}),0.024788,0.054489,0.011538,0.465464,8.542365,1.0,0.010187,1.768843,0.905379,0.170327,0.434659,0.338605,1,1
34,frozenset({50502436}),frozenset({50689433}),0.054489,0.032198,0.008603,0.157887,4.903643,1.0,0.006849,1.149255,0.841947,0.110178,0.129871,0.212541,1,1
35,frozenset({50689433}),frozenset({50502436}),0.032198,0.054489,0.008603,0.267194,4.903643,1.0,0.006849,1.290261,0.822555,0.110178,0.224963,0.212541,1,1
36,frozenset({50502436}),frozenset({54550994}),0.054489,0.061543,0.007002,0.128494,2.087887,1.0,0.003648,1.076823,0.551074,0.064216,0.071342,0.121130,1,1
37,frozenset({54550994}),frozenset({50502436}),0.061543,0.054489,0.007002,0.113767,2.087887,1.0,0.003648,1.066887,0.555216,0.064216,0.062694,0.121130,1,1
38,frozenset({50502436}),frozenset({62816594}),0.054489,0.029026,0.007026,0.128947,4.442392,1.0,0.005445,1.114712,0.819553,0.091858,0.102907,0.185504,1,1
39,frozenset({62816594}),frozenset({50502436}),0.029026,0.054489,0.007026,0.242061,4.442392,1.0,0.005445,1.247476,0.798061,0.091858,0.198382,0.185504,1,1
40,frozenset({50502436}),frozenset({75341714}),0.054489,0.017185,0.006015,0.110383,6.423333,1.0,0.005078,1.104763,0.892975,0.091605,0.094828,0.230192,1,1
41,frozenset({75341714}),frozenset({50502436}),0.017185,0.054489,0.006015,0.350000,6.423333,1.0,0.005078,1.454633,0.859081,0.091605,0.312541,0.230192,1,1
42,frozenset({50502436}),frozenset({77454543}),0.054489,0.019999,0.007180,0.131764,6.588420,1.0,0.006090,1.128726,0.897101,0.106668,0.114046,0.245380,1,1
43,frozenset({77454543}),frozenset({50502436}),0.019999,0.054489,0.007180,0.358995,6.588420,1.0,0.006090,1.475046,0.865529,0.106668,0.322055,0.245380,1,1
44,frozenset({50503441}),frozenset({50550228}),0.036397,0.020380,0.005193,0.142686,7.001383,1.0,0.004452,1.142662,0.889548,0.100679,0.124851,0.198757,1,1
45,frozenset({50550228}),frozenset({50503441}),0.020380,0.036397,0.005193,0.254828,7.001383,1.0,0.004452,1.293129,0.875003,0.100679,0.226682,0.198757,1,1
46,frozenset({54550994}),frozenset({50503441}),0.061543,0.036397,0.005349,0.086921,2.388152,1.0,0.003109,1.055334,0.619385,0.057775,0.052433,0.116947,1,1
47,frozenset({50503441}),frozenset({54550994}),0.036397,0.061543,0.005349,0.146974,2.388152,1.0,0.003109,1.100150,0.603222,0.057775,0.091033,0.116947,1,1
48,frozenset({50503441}),frozenset({62816594}),0.036397,0.029026,0.005358,0.147217,5.071818,1.0,0.004302,1.138593,0.833156,0.089207,0.121723,0.165907,1,1
49,frozenset({62816594}),frozenset({50503441}),0.029026,0.036397,0.005358,0.184598,5.071818,1.0,0.004302,1.181753,0.826832,0.089207,0.153799,0.165907,1,1
50,frozenset({50550228}),frozenset({62816594}),0.020380,0.029026,0.005325,0.261308,9.002415,1.0,0.004734,1.314449,0.907411,0.120810,0.239225,0.222387,1,1
51,frozenset({62816594}),frozenset({50550228}),0.029026,0.020380,0.005325,0.183466,9.002415,1.0,0.004734,1.199731,0.915492,0.120810,0.166480,0.222387,1,1

In [23]:
# 53482131 = id of Kettle Chips Sea Salt And Black Pepper Corns 150G
# probably need to first conver the item ids into names

# This atleast does not seem to be working, but could also just be because I have not actually set the min support low enough originally?
rules[ (rules['antecedents'] == frozenset({53482131})) &
       (rules['lift'] >= 1.05) ]

Empty DataFrame
Columns: [antecedents, consequents, antecedent support, consequent support, support, confidence, lift, representativity, leverage, conviction, zhangs_metric, jaccard, certainty, kulczynski, antecedent_len, consequents_len]
Index: []